// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4xbr0f0znVREV3BHFv8cuvadQLYKANxI',
    appId: '1:100785195709:web:7df655ca01637682bdc5d4',
    messagingSenderId: '100785195709',
    projectId: 'todolistapp-77e7b',
    authDomain: 'todolistapp-77e7b.firebaseapp.com',
    storageBucket: 'todolistapp-77e7b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx8M5x5wijna8wCK-UqHKSwmcFqx1bVqw',
    appId: '1:100785195709:android:57ed6c96e6dda18fbdc5d4',
    messagingSenderId: '100785195709',
    projectId: 'todolistapp-77e7b',
    storageBucket: 'todolistapp-77e7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOcGb_Bqzd-6NggmjIvwDfVEAV1bH3ThA',
    appId: '1:100785195709:ios:e87418df1e969ed4bdc5d4',
    messagingSenderId: '100785195709',
    projectId: 'todolistapp-77e7b',
    storageBucket: 'todolistapp-77e7b.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOcGb_Bqzd-6NggmjIvwDfVEAV1bH3ThA',
    appId: '1:100785195709:ios:e87418df1e969ed4bdc5d4',
    messagingSenderId: '100785195709',
    projectId: 'todolistapp-77e7b',
    storageBucket: 'todolistapp-77e7b.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4xbr0f0znVREV3BHFv8cuvadQLYKANxI',
    appId: '1:100785195709:web:b52b61443aa3efdbbdc5d4',
    messagingSenderId: '100785195709',
    projectId: 'todolistapp-77e7b',
    authDomain: 'todolistapp-77e7b.firebaseapp.com',
    storageBucket: 'todolistapp-77e7b.appspot.com',
  );
}
